### ISSUE TITLE
Having issue using eth-query with async and await

### ISSUE THREAD

**Issue by pravin-d** [ethereumjs/eth-query#5]
I'm trying to use the eth-query with angular5 project. The project is created using angular-cli.
The current api provided by eth-query all use callbacks. Can someone help with setting up the transpilation (webpack and angular-cli) for transforming the current eth-query code to work with es6 async/await?

**Comment by SilentCicero** [comment]
Checkout ethjs-rpc, ethjs-query or ethrpc ;)
